workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.mubarakapp"
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - andrepierre585@gmail.com
        notify:
          success: true
          failure: true

  expo-android:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_credentials
      vars:
        PACKAGE_NAME: "com.mubarakapp"
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli eas-cli
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform android --clean
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - andrepierre585@gmail.com
        notify:
          success: true
          failure: true

  expo-ios:
    name: Expo iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
        - ios_signing
      vars:
        BUNDLE_ID: "com.mubarakapp"
        XCODE_WORKSPACE: "ios/MubarakApp.xcworkspace"
        XCODE_SCHEME: "MubarakApp"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli eas-cli
      - name: Expo prebuild iOS
        script: |
          npx expo prebuild --platform ios --clean
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - andrepierre585@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: false
